mini_set: 1000

contact_margin: 0.01  # unit: m
contact_threshold: 0.002
max_pene: 0.01

obj_mass: 0.1   # unit: kg 
miu_coef: [0.6, 0.02]
force_closure: True
squeeze_type: "real" # "real" or "heuristic"
squeeze_ratio: 1 # squeeze=(grasp-pregrasp)*squeeze_ratio+grasp
pregrasp_type: "multiply" # "real" or "minus" or "multiply"
pregrasp_minus: 0.05 # pregrasp=grasp-pg_minus
pregrasp_multiply: 0.9 # pregrasp=grasp*pg_multiply