skip: True
n_worker: 48    

exp_name: debug
save_root: output
save_dir: ${save_root}/${exp_name}_${hand_name}
grasp_dir: ${save_dir}/graspdata
eval_dir: ${save_dir}/evaluation
succ_dir: ${save_dir}/succgrasp
vusd_dir: ${save_dir}/visualization_usd
vobj_dir: ${save_dir}/visualization_obj
data_struct: 
  - "**"
  - "**"
  - "**.npy"

log_dir: ${save_dir}/log/${task_name}/${now:%Y_%m_%d_%H_%M_%S}
log_path: ${log_dir}/../path_log.txt

debug: False
debug_viewer: False
debug_render: False

defaults:
  - _self_
  - task: stat
  - hand: shadow

task_name: ${hydra:runtime.choices.task}
hand_name: ${hydra:runtime.choices.hand}

hydra:
  run:
    dir: ${log_dir}